from __future__ import annotations
from app.schemas.endereco import *
from app.schemas.pessoa import *
from app.schemas.funcionario import *
from app.schemas.dependente import *
from app.schemas.diretor import *
from app.schemas.gerente import *
from app.schemas.pessoa_operacional import *
from app.schemas.cozinheiro import *
from app.schemas.camareiro import *
from app.schemas.auxiliar_servicos_gerais import *
from app.schemas.recepcionista import *
from app.schemas.idioma_recepcionista import *
from app.schemas.reserva import *
from app.schemas.titular_financeiro import *
from app.schemas.hospede import *
from app.schemas.empresa import *
from app.schemas.pagamento import *
from app.schemas.categoria_quarto import *
from app.schemas.quarto import *
from app.schemas.reserva_quarto import *
from app.schemas.item import *
from app.schemas.consome import *
